apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
        - name: go-web
          image: nginx   # replace later with your ECR image
          ports:
            - containerPort: 8080